name: CI pipeline

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: python install
      uses: actions/python@v4
      with:
        python-version: "3.10"
      
    - name : install dependency
      run: pip install -r requirements.txt
    - name: train model
      run: python train.py

    - name: pylint test
      run: pylint *.py || true

    - name: pytest test
      run: pytest